[files]
extend-exclude = []
ignore-hidden = false
ignore-files = false
ignore-dot = false
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = false
unicode = true
locale = "en"
extend-ignore-re = [
    # Ignore lines that end with `# spellchecker:disable-line`
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
    # Ignore the line after `# spellchecker:ignore-next-line`:
    "(#|//)\\s*spellchecker:ignore-next-line\\n.*",
    # Ignore blocks between `# spellchecker:off` and `# spellchecker:on`
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]
extend-ignore-identifiers-re = []
extend-ignore-words-re = []

[default.extend-words]
noice = "noice"
indx = "indx"
onfig = "onfig"

[default.extend-identifiers]
# <typo> = "<correction>"
